"""f0.3 identity gate: every pushed ref (branches and tags) is scanned.

Verified defects this file pins down:

* the pre-push hook generated by scripts/install-hooks.sh only ran push_gate.sh
  for refs/heads/main|master, so tags and every other branch were never
  scanned (the public f0.2 tag object carries a tagger address on a private
  IPv4 host);
* scripts/commit_metadata_scan.py only read commit author/committer, never an
  annotated tag's tagger;
* its forbidden-domain rule only knew numeric IPv4 and ``.local``, so
  ``ops@build-01.internal`` or an Aliyun default host name passed.

Every behaviour test here runs real git in throw-away repositories under
tmp_path, and each fix is paired with a negative control showing that the
previous code let the same fixture through.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from scripts import commit_metadata_scan as cms

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
CLEAN = ("monkey2jack", "monkey2jack@users.noreply.github.com")
WORD = "synthetic-private-fragment-7c41"
# 扫描报告的原文字段：被拦要能分清「判了红」与「扫描器崩了」。
FORBIDDEN_HIT = re.compile("禁止邮箱域=[1-9]")
NOT_ALLOWLISTED_HIT = re.compile("白名单外身份=[1-9]")
UNVERIFIABLE = "提交元数据扫描：不可核验"


# --------------------------------------------------------------------------
# Negative-control copies of the previous implementation (faaa9af).
# --------------------------------------------------------------------------

_OLD_NUMERIC_IPV4 = re.compile(rb"(?:[0-9]{1,3}\.){3}[0-9]{1,3}")


def _old_forbidden_email_domain(email: bytes) -> bool:
    """Verbatim copy of the faaa9af rule (numeric IPv4 and .local only)."""
    if email.count(b"@") != 1:
        return True
    domain = email.rsplit(b"@", 1)[1].lower().rstrip(b".")
    if domain.startswith(b"[") and domain.endswith(b"]"):
        domain = domain[1:-1]
    return (
        not domain
        or not bool(re.fullmatch(rb"[a-z0-9.-]+", domain))
        or any(not label or label.startswith(b"-") or label.endswith(b"-")
               for label in domain.split(b"."))
        or bool(_OLD_NUMERIC_IPV4.fullmatch(domain))
        or domain == b"local"
        or domain.endswith(b".local")
    )


# Control flow of the faaa9af pre-push hook: only main/master reached the gate.
_OLD_HOOK = """#!/usr/bin/env bash
# aidumei-pre-push-hook (faaa9af control flow)
while read -r local_ref local_sha remote_ref remote_sha; do
    if [ "$remote_ref" = "refs/heads/main" ] || [ "$remote_ref" = "refs/heads/master" ]; then
        if ! bash scripts/push_gate.sh; then
            exit 1
        fi
    fi
done
exit 0
"""

# Stand-in for the full gate: records that it ran; exit code is controllable.
_STUB_GATE = """#!/usr/bin/env bash
echo ran >> "$STUB_GATE_MARKER"
exit "${STUB_GATE_EXIT:-0}"
"""


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------

def _base_env(tmp_path: Path) -> dict[str, str]:
    env = os.environ.copy()
    for key in list(env):
        if key.startswith(("GIT_", "AIDUMEI_SCAN_", "AIDUMEI_IDENTITY_")):
            env.pop(key)
    empty = tmp_path / "empty.gitconfig"
    empty.touch()
    # Never read the developer's global/system git config (hooksPath, signing).
    env["GIT_CONFIG_GLOBAL"] = str(empty)
    env["GIT_CONFIG_NOSYSTEM"] = "1"
    env["HOME"] = str(tmp_path / "home")
    words = tmp_path / "words.txt"
    words.write_text(WORD + "\n", encoding="utf-8")
    env["AIDUMEI_SCAN_WORDLIST"] = str(words)
    env["AIDUMEM_PYTHON"] = sys.executable
    env["STUB_GATE_MARKER"] = str(tmp_path / "gate-ran.txt")
    return env


def _git(repo: Path, *args: str, env: dict[str, str], check: bool = True,
         ident: tuple[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    env = dict(env)
    if ident is not None:
        env.update({
            "GIT_AUTHOR_NAME": ident[0], "GIT_AUTHOR_EMAIL": ident[1],
            "GIT_COMMITTER_NAME": ident[0], "GIT_COMMITTER_EMAIL": ident[1],
        })
    result = subprocess.run(["git", *args], cwd=repo, env=env,
                            capture_output=True, text=True, check=False)
    if check and result.returncode:
        raise AssertionError(f"git {args} failed: {result.stdout}{result.stderr}")
    return result


class Fixture:
    def __init__(self, tmp_path: Path, hook: str = "new") -> None:
        self.tmp = tmp_path
        self.env = _base_env(tmp_path)
        self.remote = tmp_path / "remote.git"
        self.work = tmp_path / "work"
        subprocess.run(["git", "init", "-q", "--bare", str(self.remote)],
                       env=self.env, check=True, capture_output=True)
        self.work.mkdir()
        self.git("init", "-q", "-b", "main")
        for key, value in (("commit.gpgsign", "false"), ("tag.gpgsign", "false"),
                           ("user.name", CLEAN[0]), ("user.email", CLEAN[1])):
            self.git("config", key, value)
        scripts = self.work / "scripts"
        scripts.mkdir()
        for name in ("commit_metadata_scan.py", "release_scan.py", "install-hooks.sh"):
            shutil.copy2(SCRIPTS / name, scripts / name)
        (scripts / "push_gate.sh").write_text(_STUB_GATE, encoding="utf-8")
        (self.work / ".gitignore").write_text("scripts/\n", encoding="utf-8")
        self.git("remote", "add", "origin", str(self.remote))
        self.commit("baseline", CLEAN)
        self.git("push", "-q", "--no-verify", "origin", "main")
        if hook == "new":
            result = subprocess.run(["bash", "scripts/install-hooks.sh"], cwd=self.work,
                                    env=self.env, capture_output=True, text=True)
            assert result.returncode == 0, result.stdout + result.stderr
        elif hook == "old":
            hook_file = self.work / ".git" / "hooks" / "pre-push"
            hook_file.write_text(_OLD_HOOK, encoding="utf-8")
            hook_file.chmod(0o755)

    def git(self, *args: str, check: bool = True,
            ident: tuple[str, str] | None = None) -> subprocess.CompletedProcess[str]:
        return _git(self.work, *args, env=self.env, check=check, ident=ident)

    def commit(self, message: str, ident: tuple[str, str]) -> str:
        self.git("commit", "-q", "--allow-empty", "-m", message, ident=ident)
        return self.git("rev-parse", "HEAD").stdout.strip()

    def tag(self, name: str, tagger: tuple[str, str], target: str = "HEAD") -> None:
        self.git("tag", "-a", name, "-m", f"release {name}", target, ident=tagger)

    def push(self, *refspecs: str, **extra: str) -> subprocess.CompletedProcess[str]:
        env = dict(self.env, **extra)
        return subprocess.run(["git", "push", "origin", *refspecs], cwd=self.work,
                              env=env, capture_output=True, text=True, check=False)

    def remote_has(self, ref: str) -> bool:
        return subprocess.run(["git", "--git-dir", str(self.remote), "rev-parse", "--verify",
                               "-q", ref], env=self.env, capture_output=True).returncode == 0

    @property
    def gate_ran(self) -> bool:
        return Path(self.env["STUB_GATE_MARKER"]).exists()


# --------------------------------------------------------------------------
# Forbidden e-mail domains
# --------------------------------------------------------------------------

NEWLY_FORBIDDEN = [
    "ops@build-01.internal",
    "root@iZbp1a2b3c4d5e6f7g8h9Z",
    "root@iZbp1a2b3c4d5e6f7g8h9Z.example.com",
    "root@build-01",
    "root@localhost",
    "me@nas.lan",
    "me@router.home",
    "me@box.localdomain",
    "me@dc1.corp",
    "me@srv.intranet",
    "me@srv.private",
    "me@10.0.1",
    "me@gw.home.arpa",
    "ec2-user@ip-10-0-0-1.ec2.internal",
    "ec2-user@ec2-54-12-34-56.compute-1.amazonaws.com",
    "root@vm-0-12-centos",
]


@pytest.mark.parametrize("email", NEWLY_FORBIDDEN)
def test_new_domain_rule_rejects_private_and_cloud_hosts(email: str) -> None:
    assert cms._forbidden_email_domain(email.encode()) is True


@pytest.mark.parametrize("email", [
    "ops@build-01.internal", "root@iZbp1a2b3c4d5e6f7g8h9Z", "root@build-01",
    "me@nas.lan", "me@dc1.corp",
])
def test_negative_control_old_domain_rule_let_these_through(email: str) -> None:
    assert _old_forbidden_email_domain(email.encode()) is False
    assert cms._forbidden_email_domain(email.encode()) is True


@pytest.mark.parametrize("email", [
    "monkey2jack@users.noreply.github.com",
    "12345+someone@users.noreply.github.com",
    "noreply@github.com",
    "dev@example.com",
    "dev@mail.example.org",
    "someone@home.nl",
    "fixture@example.invalid",
])
def test_public_domains_stay_allowed(email: str) -> None:
    assert cms._forbidden_email_domain(email.encode()) is False


@pytest.mark.parametrize("email", ["tagger@192.0.2.10", "x@host.local", "x@[::1]", "a@b@c"])
def test_previous_rules_are_kept(email: str) -> None:
    assert cms._forbidden_email_domain(email.encode()) is True


# --------------------------------------------------------------------------
# Scanner API: tags, allowlist mode, pre-push input
# --------------------------------------------------------------------------

@pytest.fixture
def repo(tmp_path: Path) -> Fixture:
    return Fixture(tmp_path, hook="none")


def test_tagger_of_named_tag_is_scanned(repo: Fixture) -> None:
    repo.tag("v9.9", ("Synthetic Tagger", "tagger@192.0.2.10"))
    head = repo.git("rev-parse", "HEAD").stdout.strip()

    counts = cms.scan_commit_metadata(repo.work, head, head, [WORD], tags=["v9.9"])

    assert (counts.tags, counts.forbidden_domains, counts.blocked) == (1, 1, True)
    # Negative control: the previous push_gate call (no tag input) sees nothing.
    old_call = cms.scan_commit_metadata(repo.work, head, head, [WORD])
    assert (old_call.commits, old_call.tags, old_call.blocked) == (0, 0, False)


def test_tags_in_range_covers_head_and_new_commits_but_not_old_tags(repo: Fixture) -> None:
    base = repo.git("rev-parse", "HEAD").stdout.strip()
    repo.tag("old-release", ("Synthetic Tagger", "tagger@192.0.2.10"), target=base)
    repo.commit("new work", CLEAN)
    repo.tag("new-release", ("Ops", "ops@build-01.internal"))

    counts = cms.scan_commit_metadata(repo.work, base, "HEAD", [WORD], tags_in_range=True)
    # Only the tag on the new range is scanned; the older tag is outside BASE..HEAD.
    assert (counts.commits, counts.tags, counts.forbidden_domains) == (1, 1, 1)

    at_head = cms.scan_commit_metadata(repo.work, base, base, [WORD], tags_in_range=True)
    # A tag pointing exactly at HEAD is new even with an empty commit range.
    assert (at_head.commits, at_head.tags, at_head.forbidden_domains) == (0, 1, 1)


def test_nested_tag_chain_scans_every_tagger(repo: Fixture) -> None:
    repo.tag("inner", CLEAN)
    repo.git("tag", "-a", "outer", "-m", "outer", "inner", ident=("Ops", "ops@box.lan"))
    head = repo.git("rev-parse", "HEAD").stdout.strip()

    counts = cms.scan_commit_metadata(repo.work, head, head, [WORD], tags=["outer"])
    assert (counts.tags, counts.forbidden_domains) == (2, 1)


def test_mergetag_tagger_embedded_in_a_commit_is_scanned(repo: Fixture) -> None:
    base = repo.git("rev-parse", "HEAD").stdout.strip()
    tree = repo.git("rev-parse", "HEAD^{tree}").stdout.strip()
    ident = f"{CLEAN[0]} <{CLEAN[1]}> 1700000000 +0000"
    raw = (f"tree {tree}\nparent {base}\nauthor {ident}\ncommitter {ident}\n"
           f"mergetag object {base}\n type commit\n tag v9.9\n"
           " tagger Synthetic Tagger <tagger@192.0.2.10> 1700000000 +0000\n \n release\n"
           "\nMerge tag v9.9\n")
    sha = subprocess.run(["git", "hash-object", "-t", "commit", "-w", "--stdin"], cwd=repo.work,
                         env=repo.env, input=raw, capture_output=True, text=True,
                         check=True).stdout.strip()
    repo.git("update-ref", "refs/heads/main", sha)

    counts = cms.scan_commit_metadata(repo.work, base, "HEAD", [WORD])
    assert (counts.commits, counts.identities, counts.forbidden_domains) == (1, 3, 1)


def test_allowlist_mode_requires_project_identity_or_github_noreply(repo: Fixture) -> None:
    base = repo.git("rev-parse", "HEAD").stdout.strip()
    repo.commit("contractor", ("Dev", "dev@example.com"))

    denylist_only = cms.scan_commit_metadata(repo.work, base, "HEAD", [WORD])
    assert denylist_only.blocked is False  # public domain, no word hit: old policy passes
    strict = cms.scan_commit_metadata(repo.work, base, "HEAD", [WORD], require_allowlist=True)
    assert (strict.not_allowlisted, strict.blocked) == (2, True)  # author + committer
    allow = cms.load_identity_allowlist(["Dev <dev@example.com>"], env={})
    allowed = cms.scan_commit_metadata(repo.work, base, "HEAD", [WORD],
                                       require_allowlist=True, allow=allow)
    assert (allowed.not_allowlisted, allowed.blocked) == (0, False)


def test_allowlist_accepts_github_noreply_forms(repo: Fixture) -> None:
    base = repo.git("rev-parse", "HEAD").stdout.strip()
    repo.commit("bot", ("github-actions[bot]",
                        "41898282+github-actions[bot]@users.noreply.github.com"))
    repo.git("commit", "-q", "--allow-empty", "-m", "web merge", ident=("GitHub", "noreply@github.com"))
    counts = cms.scan_commit_metadata(repo.work, base, "HEAD", [WORD], require_allowlist=True)
    assert (counts.commits, counts.not_allowlisted) == (2, 0)


@pytest.mark.parametrize("entry", ["no-brackets@example.com", "Name <>", "<a@b.c>", "Name <a b@c.d>"])
def test_malformed_allowlist_entry_is_unverifiable(entry: str) -> None:
    with pytest.raises(cms.MetadataScanError):
        cms.load_identity_allowlist([entry], env={})


def test_allowlist_env_entries_are_split_on_semicolons() -> None:
    allow = cms.load_identity_allowlist(
        [], env={"AIDUMEI_IDENTITY_ALLOWLIST": "A Bot <a@example.org>; B <b@example.org>\n"})
    assert allow == {(b"A Bot", b"a@example.org"), (b"B", b"b@example.org")}


def _line(local_ref: str, local_sha: str, remote_ref: str, remote_sha: str) -> str:
    return f"{local_ref} {local_sha} {remote_ref} {remote_sha}"


ZERO = "0" * 40


def test_pre_push_excludes_commits_the_remote_already_has(repo: Fixture) -> None:
    # A private identity that is already public on origin/main is history, not news.
    repo.commit("old private", ("Synthetic Tagger", "tagger@192.0.2.10"))
    repo.git("push", "-q", "--no-verify", "origin", "main")
    old = repo.git("rev-parse", "HEAD").stdout.strip()
    new = repo.commit("clean", CLEAN)

    counts = cms.scan_pre_push(repo.work, "origin",
                               [_line("refs/heads/main", new, "refs/heads/main", old)], [WORD],
                               require_allowlist=True)
    assert (counts.refs, counts.commits, counts.forbidden_domains, counts.blocked) == (1, 1, 0, False)


def test_pre_push_scans_tags_and_other_branches(repo: Fixture) -> None:
    repo.git("checkout", "-q", "-b", "feature")
    feature = repo.commit("feature", ("Ops", "ops@build-01.internal"))
    repo.tag("v9.9", ("Synthetic Tagger", "tagger@192.0.2.10"))
    tag_sha = repo.git("rev-parse", "refs/tags/v9.9").stdout.strip()

    counts = cms.scan_pre_push(repo.work, "origin", [
        _line("refs/heads/feature", feature, "refs/heads/feature", ZERO),
        _line("refs/tags/v9.9", tag_sha, "refs/tags/v9.9", ZERO),
    ], [WORD])
    # One new commit (author + committer) and one tagger, all on private hosts.
    assert (counts.refs, counts.commits, counts.tags, counts.forbidden_domains) == (2, 1, 1, 3)


def test_pre_push_deletion_pushes_nothing(repo: Fixture) -> None:
    head = repo.git("rev-parse", "HEAD").stdout.strip()
    counts = cms.scan_pre_push(repo.work, "origin",
                               [_line("(delete)", ZERO, "refs/heads/gone", head)], [WORD])
    assert (counts.refs, counts.commits, counts.tags, counts.blocked) == (1, 0, 0, False)


@pytest.mark.parametrize("line", [
    "refs/heads/main deadbeef refs/heads/main " + ZERO,
    "only three fields",
    "refs/heads/main " + "g" * 40 + " refs/heads/main " + ZERO,
])
def test_pre_push_malformed_input_is_unverifiable(repo: Fixture, line: str) -> None:
    with pytest.raises(cms.MetadataScanError):
        cms.scan_pre_push(repo.work, "origin", [line], [WORD])


@pytest.mark.parametrize("remote", ["", "--all", "orig*"])
def test_pre_push_rejects_unsafe_remote_names(repo: Fixture, remote: str) -> None:
    with pytest.raises(cms.MetadataScanError):
        cms.scan_pre_push(repo.work, remote, [], [WORD])


def test_cli_reports_counts_without_leaking_identities(repo: Fixture) -> None:
    repo.tag("v9.9", ("Synthetic Private", "tagger@192.0.2.10"))
    head = repo.git("rev-parse", "HEAD").stdout.strip()
    result = subprocess.run(
        [sys.executable, str(SCRIPTS / "commit_metadata_scan.py"), "--base", head,
         "--head", head, "--tag", "v9.9", "--require-allowlist"],
        cwd=repo.work, env=repo.env, capture_output=True, text=True, check=False)
    assert result.returncode == 1, result.stdout + result.stderr
    output = result.stdout + result.stderr
    for secret in ("Synthetic Private", "tagger@", "192.0.2.10"):
        assert secret not in output


# --------------------------------------------------------------------------
# The real pre-push hook, driven by real `git push`
# --------------------------------------------------------------------------

def test_hook_blocks_other_branch_with_internal_host_author(tmp_path: Path) -> None:
    fx = Fixture(tmp_path)
    fx.git("checkout", "-q", "-b", "feature")
    fx.commit("feature", ("Ops", "ops@build-01.internal"))

    result = fx.push("feature")

    assert result.returncode != 0, result.stdout + result.stderr
    assert FORBIDDEN_HIT.search(result.stdout) and UNVERIFIABLE not in result.stdout
    assert not fx.remote_has("refs/heads/feature")
    assert not fx.gate_ran  # the identity gate stops it before any full gate


def test_negative_control_old_hook_pushed_that_branch(tmp_path: Path) -> None:
    fx = Fixture(tmp_path, hook="old")
    fx.git("checkout", "-q", "-b", "feature")
    fx.commit("feature", ("Ops", "ops@build-01.internal"))

    result = fx.push("feature")

    assert result.returncode == 0, result.stdout + result.stderr
    assert fx.remote_has("refs/heads/feature")


@pytest.mark.parametrize("tagger", [("Synthetic Tagger", "tagger@192.0.2.10"),
                                    ("root", "root@iZbp1a2b3c4d5e6f7g8h9Z")])
def test_hook_blocks_tag_with_private_tagger(tmp_path: Path, tagger: tuple[str, str]) -> None:
    fx = Fixture(tmp_path)
    fx.tag("v9.9", tagger)

    result = fx.push("refs/tags/v9.9")

    assert result.returncode != 0, result.stdout + result.stderr
    assert FORBIDDEN_HIT.search(result.stdout) and UNVERIFIABLE not in result.stdout
    assert not fx.remote_has("refs/tags/v9.9")


def test_negative_control_old_hook_pushed_the_private_tag(tmp_path: Path) -> None:
    fx = Fixture(tmp_path, hook="old")
    fx.tag("v9.9", ("Synthetic Tagger", "tagger@192.0.2.10"))

    result = fx.push("refs/tags/v9.9")

    assert result.returncode == 0, result.stdout + result.stderr
    assert fx.remote_has("refs/tags/v9.9")


def test_hook_blocks_identity_outside_allowlist(tmp_path: Path) -> None:
    fx = Fixture(tmp_path)
    fx.git("checkout", "-q", "-b", "feature")
    fx.commit("contractor", ("Dev", "dev@example.com"))

    blocked = fx.push("feature")
    assert blocked.returncode != 0
    assert NOT_ALLOWLISTED_HIT.search(blocked.stdout) and not FORBIDDEN_HIT.search(blocked.stdout)
    assert not fx.remote_has("refs/heads/feature")
    extended = fx.push("feature", AIDUMEI_IDENTITY_ALLOWLIST="Dev <dev@example.com>")
    assert extended.returncode == 0, extended.stdout + extended.stderr


def test_hook_passes_clean_refs_and_runs_full_gate_only_for_main(tmp_path: Path) -> None:
    fx = Fixture(tmp_path)
    fx.git("checkout", "-q", "-b", "feature")
    fx.commit("feature", CLEAN)
    fx.tag("v9.9", CLEAN)

    assert fx.push("feature", "refs/tags/v9.9").returncode == 0
    assert fx.remote_has("refs/heads/feature") and fx.remote_has("refs/tags/v9.9")
    assert not fx.gate_ran

    fx.git("checkout", "-q", "main")
    fx.commit("main work", CLEAN)
    result = fx.push("main")
    assert result.returncode == 0, result.stdout + result.stderr
    assert fx.gate_ran


def test_hook_keeps_full_gate_failure_blocking_main(tmp_path: Path) -> None:
    fx = Fixture(tmp_path)
    fx.commit("main work", CLEAN)
    before = subprocess.run(["git", "--git-dir", str(fx.remote), "rev-parse", "refs/heads/main"],
                            env=fx.env, capture_output=True, text=True).stdout

    result = fx.push("main", STUB_GATE_EXIT="1")

    assert result.returncode != 0 and fx.gate_ran
    after = subprocess.run(["git", "--git-dir", str(fx.remote), "rev-parse", "refs/heads/main"],
                           env=fx.env, capture_output=True, text=True).stdout
    assert before == after


def test_hook_fails_closed_without_wordlist(tmp_path: Path) -> None:
    fx = Fixture(tmp_path)
    fx.git("checkout", "-q", "-b", "feature")
    fx.commit("feature", CLEAN)
    fx.env.pop("AIDUMEI_SCAN_WORDLIST")  # default path under the empty HOME is absent

    result = fx.push("feature")
    assert result.returncode != 0 and UNVERIFIABLE in result.stdout
    assert not fx.remote_has("refs/heads/feature")


# --------------------------------------------------------------------------
# install-hooks.sh itself
# --------------------------------------------------------------------------

def _install(cwd: Path, env: dict[str, str], *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["bash", str(SCRIPTS / "install-hooks.sh"), *args], cwd=cwd,
                          env=env, capture_output=True, text=True, check=False)


def test_install_hooks_supports_linked_worktrees(tmp_path: Path) -> None:
    fx = Fixture(tmp_path, hook="none")
    wt = tmp_path / "wt"
    fx.git("worktree", "add", "-q", "-b", "side", str(wt))
    assert (wt / ".git").is_file()  # linked worktree: .git is a file

    result = _install(wt, fx.env)

    assert result.returncode == 0, result.stdout + result.stderr
    hook = fx.work / ".git" / "hooks" / "pre-push"
    assert hook.is_file() and os.access(hook, os.X_OK)
    assert _install(wt, fx.env, "--check").returncode == 0
    assert subprocess.run(["bash", "-n", str(hook)], capture_output=True).returncode == 0


def test_install_hooks_upgrades_old_hook_and_refuses_foreign_hook(tmp_path: Path) -> None:
    fx = Fixture(tmp_path, hook="old")
    hook = fx.work / ".git" / "hooks" / "pre-push"

    assert _install(fx.work, fx.env, "--check").returncode == 1  # old version is not current
    assert _install(fx.work, fx.env).returncode == 0
    assert "--pre-push" in hook.read_text(encoding="utf-8")
    assert _install(fx.work, fx.env, "--check").returncode == 0

    foreign = "#!/bin/sh\necho someone else's hook\n"
    hook.write_text(foreign, encoding="utf-8")
    assert _install(fx.work, fx.env).returncode == 1
    assert hook.read_text(encoding="utf-8") == foreign


def test_push_gate_uses_tag_scan_and_allowlist_mode() -> None:
    source = (SCRIPTS / "push_gate.sh").read_text(encoding="utf-8")
    call = source[source.index("scripts/commit_metadata_scan.py"):]
    call = call[:call.index("|| fail")]
    assert "--tags-in-range" in call and "--require-allowlist" in call
    assert subprocess.run(["bash", "-n", str(SCRIPTS / "push_gate.sh")]).returncode == 0
